function pre_install(desc)
    mkdir('inst')
    movefile({'+pooldef'...
              'extrafunctions'...
              'batch.m'...
              'jobClass.m'...
              'poolClass.m'...
              'taskClass.m'...
              'workerClass.m'...
              },'inst');
end
